# Generated by Django 5.2.6 on 2025-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saluni_kike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='region',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='street',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
