# Generated by Django 5.2.6 on 2025-09-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saluni_kike', '0002_salon_district_salon_region_salon_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
