# Generated by Django 5.2.6 on 2025-09-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saluni_kike', '0003_salon_facebook_salon_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='photo',
            new_name='photo_url',
        ),
        migrations.AlterField(
            model_name='stylist',
            name='specialties',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
