# Generated by Django 5.2.7 on 2025-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saluni_kiume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleservice',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
