# Generated by Django 5.2.7 on 2025-10-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saluni_kiume', '0002_maleservice_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malestylist',
            name='specialties',
        ),
    ]
